# Wolf Sheep Predation

## Overview

This document is used to test [NetLogo GitHub Actions](https://github.com/danielvartan/netlogo-actions) by running experiments with the *Wolf Sheep Predation* model using [Quarto](https://quarto.org/) and the [`logolink`](https://danielvartan.github.io/logolink/) R package.

## Set the Environment

### Load Packages

```{r}
#| label: Set the Environment
#| output: false

library(dplyr)
library(ggplot2)
library(logolink) # github.com/danielvartan/logolink
```

### Set Model Path

```{r}
model_path <-
  find_netlogo_home() |>
  file.path(
    "models",
    "IABM Textbook",
    "chapter 4",
    "Wolf Sheep Simple 5.nlogox"
  )
```

## Create Experiment

```{r}
#| label: Create Experiment

setup_file <- create_experiment(
  name = "Wolf Sheep Simple Model Analysis",
  repetitions = 10,
  sequential_run_order = TRUE,
  run_metrics_every_step = TRUE,
  setup = "setup",
  go = "go",
  time_limit = 1000,
  metrics = c(
    'count wolves',
    'count sheep'
  ),
  run_metrics_condition = NULL,
  constants = list(
    "number-of-sheep" = 500,
    "number-of-wolves" = list(
      first = 5,
      step = 1,
      last = 15
    ),
    "movement-cost" = 0.5,
    "grass-regrowth-rate" = 0.3,
    "energy-gain-from-grass" = 2,
    "energy-gain-from-sheep" = 5
  )
)
```

## Run Experiment

```{r}
#| label: Run Experiment
#| output: false

results <-
  model_path |>
  run_experiment(setup_file = setup_file)
```

```{r}
results |> glimpse()
```

## Analyze Results

```{r}
#| label: Analyze the Results
#| output: false

data <-
  results |>
  summarize(
    across(everything(), ~ mean(.x, na.rm = TRUE)),
    .by = c(step, number_of_wolves)
  ) |>
  arrange(number_of_wolves, step)
```

```{r}
data |>
  mutate(number_of_wolves = as.factor(number_of_wolves)) |>
  ggplot(
    aes(
      x = step,
      y = count_sheep,
      group = number_of_wolves,
      color = number_of_wolves
    )
  ) +
    labs(
      x = "Time Step",
      y = "Average Number of Sheep",
      color = "Wolves"
    ) +
  geom_line()
```
