on:
  push:
    branches: [main, master]

name: "setup-netlogo: Integrating with Quarto and logolink"

jobs:
  netlogo-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update Ubuntu packages
        run: sudo apt-get update

      - name: Install Ubuntu packages
        run: |
          sudo apt-get install -y \
            libfontconfig1-dev pandoc

      - name: Setup NetLogo
        uses: danielvartan/netlogo-actions/setup-netlogo@v1

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install and Initialize renv
        run: |
          install.packages("renv")
          renv::init()
        shell: Rscript {0}

      - name: Install logolink
        run: |
          renv::install("danielvartan/logolink")
          renv::snapshot()
        shell: Rscript {0}

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: quarto render

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
