name: setup-netlogo
author: Daniel Vartanian
description: |
  This GitHub Action sets up the NetLogo environment on a Linux runner by
  downloading and installing NetLogo, configuring environment variables, and
  updating the system PATH. Only versions 6.4.0 and above are supported.
inputs:
  version:
    description: |
      A single-quoted (!important) character string indicating the NetLogo
      version to use (e.g., `'7.0.2'`). Use `'release'` to get the latest
      stable release. Only versions 6.4.0 and above are supported.
    default: 'release'
  architecture:
    description: |
      A single-quoted (!important) character string indicating the NetLogo
      system architecture to use. Options are `'32'` or `'64'`.
    default: '64'
  cache:
    description: |
      A single-quoted (!important) boolean value indicating whether the NetLogo
      installation should be cached across runs.
    default: 'true'
runs:
  using: composite
  steps:
    - name: Validate arguments
      run: |
        # Validate arguments
        if [[ ! "${{inputs.version}}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]] && \
           [[ "${{inputs.version}}" != "release" ]]; then
          echo \
            "Error: Invalid version format" \
            "('${{inputs.version}}')." \
            "Use semantic versioning (e.g., '7.0.2') or use" \
            "'release' to get the latest stable release."

          exit 1
        fi

        if [[ "${{inputs.version}}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          major_version="${BASH_REMATCH[1]}"
          minor_version="${BASH_REMATCH[2]}"

          if (( major_version < 6 )) || \
             (( major_version == 6 && minor_version < 4 )) ; then
            echo \
              "Error: Unsupported NetLogo version" \
              "('${{inputs.version}}')." \
              "Only versions equal or greater than 6.4.0 are supported."

            exit 1
          fi
        fi

        if [[ "${{inputs.architecture}}" != "32" ]] && \
           [[ "${{inputs.architecture}}" != "64" ]]; then
          echo \
            "Error: Invalid architecture" \
            "('${{inputs.architecture}}')." \
            "Valid options are '32' or '64'."

          exit 1
        fi

        if [[ "${{inputs.cache}}" != "true" ]] && \
           [[ "${{inputs.cache}}" != "false" ]]; then
          echo \
            "Error: Invalid cache option" \
            "('${{inputs.cache}}')." \
            "Valid options are 'true' or 'false'."

          exit 1
        fi
      shell: bash

    - name: Determine NetLogo version
      id: netlogo-version
      run: |
        # Determine NetLogo version
        if [[ "${{inputs.version}}" == "release" ]]; then
          NETLOGO_VERSION=$( \
            curl -s \
              https://api.github.com/repos/NetLogo/NetLogo/releases/latest \
              | grep -oP '"tag_name":\s*"\Kv?[0-9]+\.[0-9]+(\.[0-9]+)?' \
              | tr -d 'v' \
          )

          if [[ -z "${NETLOGO_VERSION}" ]]; then
            echo \
              "Error: Could not fetch latest NetLogo version from GitHub API."

            exit 1
          fi
        else
          NETLOGO_VERSION="${{inputs.version}}"
        fi

        echo "version=${NETLOGO_VERSION}" >> "${GITHUB_OUTPUT}"
        echo "NETLOGO_VERSION=${NETLOGO_VERSION}" >> "${GITHUB_ENV}"
      shell: bash

    - name: Restore NetLogo cache
      id: netlogo-cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: "/opt/NetLogo-${{steps.netlogo-version.outputs.version}}"
        key: "netlogo-${{steps.netlogo-version.outputs.version}}-${{inputs.architecture}}"

    - name: Download NetLogo
      id: netlogo-download
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Download NetLogo
        release_api_url=$(
          printf "%s%s" \
            "https://api.github.com/repos/NetLogo/NetLogo/releases/tags/" \
            "v${NETLOGO_VERSION}" \
        )

        download_url_regex=$(
          printf "%s%s" \
            '\"browser_download_url\":\s*\"\K[^"]+' \
            "${{inputs.architecture}}\.tgz" \
        )

        download_url=$( \
          curl -s "${release_api_url}" \
          | grep -oP "${download_url_regex}" \
          | head -1 \
        )

        if [[ -z "${download_url}" ]]; then
          echo \
            "Error: Could not find download URL for NetLogo" \
            "${NETLOGO_VERSION} (${{inputs.architecture}}-bit)."

          exit 1
        fi

        tarball="/tmp/$(basename "${download_url}")"

        wget \
          "${download_url}" -qO "${tarball}" || \
          { echo "Error: Download failed"; exit 1; }

        echo "tarball=${tarball}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Install NetLogo
      if: |
        inputs.cache != 'true' ||
        steps.netlogo-cache.outputs.cache-hit != 'true'
      run: |
        # Install NetLogo
        NETLOGO_HOME="/opt/NetLogo-${NETLOGO_VERSION}"

        tarball="${{steps.netlogo-download.outputs.tarball}}"

        netlogo_console_path=$( \
          tar -tzf "${tarball}" \
          | grep "_Console$" \
          | head -1 \
        )

        if [[ -z "${netlogo_console_path}" ]]; then
          echo "Error: NetLogo_Console not found in tarball."
          exit 1
        fi

        netlogo_console_dir=$(dirname "${netlogo_console_path}")

        sudo mkdir -p "${NETLOGO_HOME}"

        if [[ "${netlogo_console_dir}" == "." ]]; then
          sudo tar \
            -xzf "${tarball}" \
            -C "${NETLOGO_HOME}"
        else
          sudo tar \
            -xzf "${tarball}" \
            -C "${NETLOGO_HOME}" \
            --strip-components=1
        fi

        rm -f "${tarball}"
      shell: bash

    - name: Set environment variables
      run: |
        # Set environment variables
        NETLOGO_HOME="/opt/NetLogo-${NETLOGO_VERSION}"

        echo "NETLOGO_HOME=${NETLOGO_HOME}" >> "${GITHUB_ENV}"
        echo "NETLOGO_CONSOLE=${NETLOGO_HOME}/NetLogo_Console" >> "${GITHUB_ENV}"

        echo "${NETLOGO_HOME}" >> "${GITHUB_PATH}"
      shell: bash

    - name: Create symbolic links
      run: |
        # Create symbolic links
        sudo ln -sf \
          "${NETLOGO_HOME}/bin/NetLogo" \
          /usr/local/bin/NetLogo

        sudo ln -sf \
          "${NETLOGO_HOME}/bin/NetLogo" \
          /usr/local/bin/netlogo
      shell: bash

    - name: Test NetLogo installation
      run: |
        # Test NetLogo installation
        netlogo --headless --version
      shell: bash
